- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: EnterpriseSoftwarePlayground (edc7ef06-fab8-4177-a907-a15cd5ef7611)
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show